export const productTypes = {
  FETCH_PRODUCTS_WITH_FILTER_START: 'FETCH_PRODUCTS_WITH_FILTER_START',
  FETCH_PRODUCTS_WITH_FILTER_SUCCESS: 'FETCH_PRODUCTS_WITH_FILTER_SUCCESS',
  FETCH_PRODUCTS_WITH_FILTER_FAILURE: 'FETCH_PRODUCTS_WITH_FILTER_FAILURE',
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  SET_PRODUCT_INFO: 'SET_PRODUCT_INFO',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_A_PRODUCT: 'GET_A_PRODUCT'
};
